### ISSUE TITLE
请问新版固件是否支持Winbond W25N01KV 芯片

### ISSUE THREAD

**Issue by 5431** [Ljzkirito/Actions-ImmortalWrt#2]
请问新版固件是否支持Winbond W25N01KV 芯片

**Comment by Ljzkirito** [comment]
抱歉，我不知道。去固件仓库问问吧^_^
[hanwckf/immortalwrt-mt798x](https://github.com/hanwckf/immortalwrt-mt798x)
[hanwckf/bl-mt798x](https://github.com/hanwckf/bl-mt798x)
